AWSTemplateFormatVersion: '2010-09-09'
Description: Spring Boot ECS Stack with ECR and ECS

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  SpringBootTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: SpringBootTaskDefinition
      NetworkMode: "awsvpc"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: calculator-app
          Image: 201964534042.dkr.ecr.us-east-1.amazonaws.com/microservice-repo:latest
          Essential: true
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: dev

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: SpringBootCluster

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: ECSCluster
      TaskDefinition:
        Ref: SpringBootTaskDefinition
      DesiredCount: 1
      LaunchType: "FARGATE"
      LoadBalancers:
        - ContainerName: calculator-container
          ContainerPort: 8080
          TargetGroupArn:
            Fn::GetAtt:
              - SpringBootTargetGroup
              - Arn

  SpringBootSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SpringBootSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SpringBootTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: SpringBootTargetGroup
      Port: 8080
      Protocol: HTTP
      VpcId:
        Fn::GetAtt:
          - ECSCluster
          - VpcId

Outputs:
  SpringBootRestEndpoint:
    Value:
      Fn::Join:
        - ""
        -
          - http://
          -
            Fn::GetAtt:
              - SpringBootTargetGroup
              - DnsName
