AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation Template to create an SQS Queue with dlq
Resources:
  SimpleDataDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: simple-data-dlq

  SimpleDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: simple-data-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SimpleDataDlq.Arn
        maxReceiveCount: 5
      VisibilityTimeout:  60
      MessageRetentionPeriod:  7200

Outputs:
  MainQueueURL:
    Description: "URL of the main SQS queue"
    Value: !Ref SimpleDataQueue

  DLQURL:
    Description: "URL of the dead letter queue"
    Value: !Ref SimpleDataDlq