AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation Template to create an SQS Queue
Resources:
  SimpleDataQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "simple-data-queue"
      VisibilityTimeout: 60       # Timeout in seconds (default is 30)
      MessageRetentionPeriod: 7200  # Message retention period in seconds (14 days max)
      DelaySeconds: 0            # Delay before messages are delivered
      MaximumMessageSize: 262144 # Max size of a message in bytes (default 256 KB)
      ReceiveMessageWaitTimeSeconds: 0  # Long polling wait time (0-20 seconds)
      Tags:
        - Key: "Environment"
          Value: "Development"

Outputs:
  QueueURL:
    Description: URL of the created SQS queue
    Value: !Ref SimpleDataQueue
    Export:
      Name: QueueURL

  QueueArn:
    Description: ARN of the created SQS queue
    Value: !GetAtt SimpleDataQueue.Arn
    Export:
      Name: QueueArn