Capabilities: CAPABILITY_NAMED_IAM
GlobalComponentName: '${shortname}-${site}-${solution}-${environment}'
RegionalComponentName: '${shortname}-${solution}-${environment}'
DockerRegistryUrl: 356026449505.dkr.ecr.eu-west-1.amazonaws.com
SslPolicy: 'ELBSecurityPolicy-FS-1-2-2019-08'
DesiredTaskCount: 1
MinTaskCount: 1
MaxTaskCount: 3
CpuSize: 512
CpuUsage: 60
MemorySize: 1GB
